/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE sedeBaseService PLEASE EDIT ../sede.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { AngularFirestore, AngularFirestoreDocument, AngularFirestoreCollection, DocumentReference } from '@angular/fire/firestore';
import { AngularFireFunctions } from '@angular/fire/functions';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Sede } from '../../domain/my-contacts_db/sede';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Sede.service.ts
 */

/*
 * SCHEMA DB Sede
 *
	{
		address: {
			type: 'String'
		},
		name: {
			type: 'String'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		sede: {
			type: Schema.ObjectId,
			ref : "Room"
		},
	}
 *
 */
@Injectable()
export class SedeBaseService {

    private sedeCollection: AngularFirestoreCollection<Sede>;
    constructor(
        private afs: AngularFirestore,
        private fns: AngularFireFunctions
    ) {
        this.sedeCollection = afs.collection<Sede>('sede');
    }


    // CRUD METHODS

    /**
    * SedeService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Sede): Promise<DocumentReference> {
        return this.sedeCollection.add(item);
    }

    /**
    * SedeService.delete
    *   @description CRUD ACTION delete
    *
    */
    remove(id: string) {
        const itemDoc: AngularFirestoreDocument<any> = this.sedeCollection.doc(id);
        itemDoc.delete();
    }

    /**
    * SedeService.get
    *   @description CRUD ACTION get
    *
    */
    get(id: string): AngularFirestoreDocument<Sede> {
        return this.afs.doc<Sede>('sede/' + id);
    }

    /**
    * SedeService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Sede[]> {
        return this.afs.collection('sede').snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as Sede;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }

    /**
    * SedeService.update
    *   @description CRUD ACTION update
    *
    */
    update(itemDoc: AngularFirestoreDocument<Sede>, item: Sede): Promise<void> {
        return itemDoc.update(item);
    }


    // Custom APIs

}
